# Generated by Django 2.1.1 on 2018-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.CharField(max_length=500)),
                ('due_date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
