# Generated by Django 2.1.1 on 2018-10-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
