# Generated by Django 2.1.1 on 2018-10-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181011_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Describe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=1000)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='list_name',
        ),
        migrations.AddField(
            model_name='describe',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.List'),
        ),
    ]
