# Generated by Django 2.1.1 on 2018-10-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181015_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due Date'),
        ),
    ]
